// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPIDemo.Data;

#nullable disable

namespace RestAPIDemo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240731133500_Added-Countries")]
    partial class AddedCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestAPIDemo.Data.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "AFG",
                            Capital = "Kabul",
                            Name = "Afghanistan",
                            Population = 38928341,
                            Size = 652230
                        },
                        new
                        {
                            Code = "ALB",
                            Capital = "Tirana",
                            Name = "Albania",
                            Population = 2877797,
                            Size = 28748
                        },
                        new
                        {
                            Code = "DZA",
                            Capital = "Algiers",
                            Name = "Algeria",
                            Population = 43851044,
                            Size = 2381741
                        },
                        new
                        {
                            Code = "AND",
                            Capital = "Andorra la Vella",
                            Name = "Andorra",
                            Population = 77265,
                            Size = 468
                        },
                        new
                        {
                            Code = "AGO",
                            Capital = "Luanda",
                            Name = "Angola",
                            Population = 32866272,
                            Size = 1246700
                        },
                        new
                        {
                            Code = "ATG",
                            Capital = "Saint John's",
                            Name = "Antigua and Barbuda",
                            Population = 97929,
                            Size = 442
                        },
                        new
                        {
                            Code = "ARG",
                            Capital = "Buenos Aires",
                            Name = "Argentina",
                            Population = 45195774,
                            Size = 2780400
                        },
                        new
                        {
                            Code = "ARM",
                            Capital = "Yerevan",
                            Name = "Armenia",
                            Population = 2963243,
                            Size = 29743
                        },
                        new
                        {
                            Code = "AUS",
                            Capital = "Canberra",
                            Name = "Australia",
                            Population = 25499884,
                            Size = 7692024
                        },
                        new
                        {
                            Code = "AUT",
                            Capital = "Vienna",
                            Name = "Austria",
                            Population = 9006398,
                            Size = 83879
                        },
                        new
                        {
                            Code = "AZE",
                            Capital = "Baku",
                            Name = "Azerbaijan",
                            Population = 10139177,
                            Size = 86600
                        },
                        new
                        {
                            Code = "BHS",
                            Capital = "Nassau",
                            Name = "Bahamas",
                            Population = 393244,
                            Size = 13943
                        },
                        new
                        {
                            Code = "BHR",
                            Capital = "Manama",
                            Name = "Bahrain",
                            Population = 1701575,
                            Size = 765
                        },
                        new
                        {
                            Code = "BGD",
                            Capital = "Dhaka",
                            Name = "Bangladesh",
                            Population = 164689383,
                            Size = 147570
                        },
                        new
                        {
                            Code = "BRB",
                            Capital = "Bridgetown",
                            Name = "Barbados",
                            Population = 287375,
                            Size = 430
                        },
                        new
                        {
                            Code = "BLR",
                            Capital = "Minsk",
                            Name = "Belarus",
                            Population = 9449323,
                            Size = 207600
                        },
                        new
                        {
                            Code = "BEL",
                            Capital = "Brussels",
                            Name = "Belgium",
                            Population = 11589623,
                            Size = 30528
                        },
                        new
                        {
                            Code = "BLZ",
                            Capital = "Belmopan",
                            Name = "Belize",
                            Population = 397628,
                            Size = 22966
                        },
                        new
                        {
                            Code = "BEN",
                            Capital = "Porto-Novo",
                            Name = "Benin",
                            Population = 12123200,
                            Size = 112622
                        },
                        new
                        {
                            Code = "BTN",
                            Capital = "Thimphu",
                            Name = "Bhutan",
                            Population = 771608,
                            Size = 38394
                        },
                        new
                        {
                            Code = "BOL",
                            Capital = "Sucre",
                            Name = "Bolivia",
                            Population = 11673021,
                            Size = 1098581
                        },
                        new
                        {
                            Code = "BIH",
                            Capital = "Sarajevo",
                            Name = "Bosnia and Herzegovina",
                            Population = 3280819,
                            Size = 51209
                        },
                        new
                        {
                            Code = "BWA",
                            Capital = "Gaborone",
                            Name = "Botswana",
                            Population = 2351627,
                            Size = 582000
                        },
                        new
                        {
                            Code = "BRA",
                            Capital = "Brasília",
                            Name = "Brazil",
                            Population = 212559417,
                            Size = 8515767
                        },
                        new
                        {
                            Code = "BRN",
                            Capital = "Bandar Seri Begawan",
                            Name = "Brunei",
                            Population = 437483,
                            Size = 5765
                        },
                        new
                        {
                            Code = "BGR",
                            Capital = "Sofia",
                            Name = "Bulgaria",
                            Population = 6948445,
                            Size = 110879
                        },
                        new
                        {
                            Code = "BFA",
                            Capital = "Ouagadougou",
                            Name = "Burkina Faso",
                            Population = 20903273,
                            Size = 272967
                        },
                        new
                        {
                            Code = "BDI",
                            Capital = "Gitega",
                            Name = "Burundi",
                            Population = 11890784,
                            Size = 27834
                        },
                        new
                        {
                            Code = "CPV",
                            Capital = "Praia",
                            Name = "Cabo Verde",
                            Population = 555987,
                            Size = 4033
                        },
                        new
                        {
                            Code = "KHM",
                            Capital = "Phnom Penh",
                            Name = "Cambodia",
                            Population = 16718965,
                            Size = 181035
                        },
                        new
                        {
                            Code = "CMR",
                            Capital = "Yaoundé",
                            Name = "Cameroon",
                            Population = 26545863,
                            Size = 475442
                        },
                        new
                        {
                            Code = "CAN",
                            Capital = "Ottawa",
                            Name = "Canada",
                            Population = 37742154,
                            Size = 9984670
                        },
                        new
                        {
                            Code = "CAF",
                            Capital = "Bangui",
                            Name = "Central African Republic",
                            Population = 4829767,
                            Size = 622984
                        },
                        new
                        {
                            Code = "TCD",
                            Capital = "N'Djamena",
                            Name = "Chad",
                            Population = 16425864,
                            Size = 1284000
                        },
                        new
                        {
                            Code = "CHL",
                            Capital = "Santiago",
                            Name = "Chile",
                            Population = 19116201,
                            Size = 756102
                        },
                        new
                        {
                            Code = "CHN",
                            Capital = "Beijing",
                            Name = "China",
                            Population = 1439323776,
                            Size = 9596961
                        },
                        new
                        {
                            Code = "COL",
                            Capital = "Bogotá",
                            Name = "Colombia",
                            Population = 50882891,
                            Size = 1141748
                        },
                        new
                        {
                            Code = "COM",
                            Capital = "Moroni",
                            Name = "Comoros",
                            Population = 869601,
                            Size = 2235
                        },
                        new
                        {
                            Code = "COG",
                            Capital = "Brazzaville",
                            Name = "Congo (Congo-Brazzaville)",
                            Population = 5518087,
                            Size = 342000
                        },
                        new
                        {
                            Code = "COD",
                            Capital = "Kinshasa",
                            Name = "Congo (Congo-Kinshasa)",
                            Population = 89561403,
                            Size = 2344858
                        },
                        new
                        {
                            Code = "CRI",
                            Capital = "San José",
                            Name = "Costa Rica",
                            Population = 5094118,
                            Size = 51100
                        },
                        new
                        {
                            Code = "HRV",
                            Capital = "Zagreb",
                            Name = "Croatia",
                            Population = 4105267,
                            Size = 56594
                        },
                        new
                        {
                            Code = "CUB",
                            Capital = "Havana",
                            Name = "Cuba",
                            Population = 11326616,
                            Size = 109884
                        },
                        new
                        {
                            Code = "CYP",
                            Capital = "Nicosia",
                            Name = "Cyprus",
                            Population = 1207359,
                            Size = 9251
                        },
                        new
                        {
                            Code = "CZE",
                            Capital = "Prague",
                            Name = "Czechia",
                            Population = 10708981,
                            Size = 78865
                        },
                        new
                        {
                            Code = "DNK",
                            Capital = "Copenhagen",
                            Name = "Denmark",
                            Population = 5818553,
                            Size = 43094
                        },
                        new
                        {
                            Code = "DJI",
                            Capital = "Djibouti",
                            Name = "Djibouti",
                            Population = 988000,
                            Size = 23200
                        },
                        new
                        {
                            Code = "DMA",
                            Capital = "Roseau",
                            Name = "Dominica",
                            Population = 71991,
                            Size = 751
                        },
                        new
                        {
                            Code = "DOM",
                            Capital = "Santo Domingo",
                            Name = "Dominican Republic",
                            Population = 10847910,
                            Size = 48671
                        },
                        new
                        {
                            Code = "ECU",
                            Capital = "Quito",
                            Name = "Ecuador",
                            Population = 17643054,
                            Size = 283561
                        },
                        new
                        {
                            Code = "EGY",
                            Capital = "Cairo",
                            Name = "Egypt",
                            Population = 102334404,
                            Size = 1002450
                        },
                        new
                        {
                            Code = "SLV",
                            Capital = "San Salvador",
                            Name = "El Salvador",
                            Population = 6486201,
                            Size = 21041
                        },
                        new
                        {
                            Code = "GNQ",
                            Capital = "Malabo",
                            Name = "Equatorial Guinea",
                            Population = 1402985,
                            Size = 28051
                        },
                        new
                        {
                            Code = "ERI",
                            Capital = "Asmara",
                            Name = "Eritrea",
                            Population = 3546000,
                            Size = 117600
                        },
                        new
                        {
                            Code = "EST",
                            Capital = "Tallinn",
                            Name = "Estonia",
                            Population = 1326535,
                            Size = 45227
                        },
                        new
                        {
                            Code = "SWZ",
                            Capital = "Mbabane",
                            Name = "Eswatini",
                            Population = 1160164,
                            Size = 17364
                        },
                        new
                        {
                            Code = "ETH",
                            Capital = "Addis Ababa",
                            Name = "Ethiopia",
                            Population = 114963588,
                            Size = 1104300
                        },
                        new
                        {
                            Code = "FJI",
                            Capital = "Suva",
                            Name = "Fiji",
                            Population = 896445,
                            Size = 18274
                        },
                        new
                        {
                            Code = "FIN",
                            Capital = "Helsinki",
                            Name = "Finland",
                            Population = 5540720,
                            Size = 338424
                        },
                        new
                        {
                            Code = "FRA",
                            Capital = "Paris",
                            Name = "France",
                            Population = 65273511,
                            Size = 551695
                        },
                        new
                        {
                            Code = "GAB",
                            Capital = "Libreville",
                            Name = "Gabon",
                            Population = 2225734,
                            Size = 267668
                        },
                        new
                        {
                            Code = "GMB",
                            Capital = "Banjul",
                            Name = "Gambia",
                            Population = 2416668,
                            Size = 11295
                        },
                        new
                        {
                            Code = "GEO",
                            Capital = "Tbilisi",
                            Name = "Georgia",
                            Population = 3989167,
                            Size = 69700
                        },
                        new
                        {
                            Code = "DEU",
                            Capital = "Berlin",
                            Name = "Germany",
                            Population = 83783942,
                            Size = 357386
                        },
                        new
                        {
                            Code = "GHA",
                            Capital = "Accra",
                            Name = "Ghana",
                            Population = 31072940,
                            Size = 238533
                        },
                        new
                        {
                            Code = "GRC",
                            Capital = "Athens",
                            Name = "Greece",
                            Population = 10423054,
                            Size = 131957
                        },
                        new
                        {
                            Code = "GRD",
                            Capital = "Saint George's",
                            Name = "Grenada",
                            Population = 112523,
                            Size = 344
                        },
                        new
                        {
                            Code = "GTM",
                            Capital = "Guatemala City",
                            Name = "Guatemala",
                            Population = 17915568,
                            Size = 108889
                        },
                        new
                        {
                            Code = "GIN",
                            Capital = "Conakry",
                            Name = "Guinea",
                            Population = 13132795,
                            Size = 245857
                        },
                        new
                        {
                            Code = "GNB",
                            Capital = "Bissau",
                            Name = "Guinea-Bissau",
                            Population = 1968001,
                            Size = 36125
                        },
                        new
                        {
                            Code = "GUY",
                            Capital = "Georgetown",
                            Name = "Guyana",
                            Population = 786559,
                            Size = 214969
                        },
                        new
                        {
                            Code = "HTI",
                            Capital = "Port-au-Prince",
                            Name = "Haiti",
                            Population = 11402528,
                            Size = 27750
                        },
                        new
                        {
                            Code = "HND",
                            Capital = "Tegucigalpa",
                            Name = "Honduras",
                            Population = 9904607,
                            Size = 112492
                        },
                        new
                        {
                            Code = "HUN",
                            Capital = "Budapest",
                            Name = "Hungary",
                            Population = 9660351,
                            Size = 93028
                        },
                        new
                        {
                            Code = "ISL",
                            Capital = "Reykjavik",
                            Name = "Iceland",
                            Population = 343599,
                            Size = 103000
                        },
                        new
                        {
                            Code = "IND",
                            Capital = "New Delhi",
                            Name = "India",
                            Population = 1380004385,
                            Size = 3287263
                        },
                        new
                        {
                            Code = "IDN",
                            Capital = "Jakarta",
                            Name = "Indonesia",
                            Population = 273523615,
                            Size = 1904569
                        },
                        new
                        {
                            Code = "IRN",
                            Capital = "Tehran",
                            Name = "Iran",
                            Population = 83992949,
                            Size = 1648195
                        },
                        new
                        {
                            Code = "IRQ",
                            Capital = "Baghdad",
                            Name = "Iraq",
                            Population = 40222493,
                            Size = 438317
                        },
                        new
                        {
                            Code = "IRL",
                            Capital = "Dublin",
                            Name = "Ireland",
                            Population = 4937786,
                            Size = 70273
                        },
                        new
                        {
                            Code = "ISR",
                            Capital = "Jerusalem",
                            Name = "Israel",
                            Population = 8655535,
                            Size = 20770
                        },
                        new
                        {
                            Code = "ITA",
                            Capital = "Rome",
                            Name = "Italy",
                            Population = 60244639,
                            Size = 301340
                        },
                        new
                        {
                            Code = "JAM",
                            Capital = "Kingston",
                            Name = "Jamaica",
                            Population = 2961161,
                            Size = 10991
                        },
                        new
                        {
                            Code = "JPN",
                            Capital = "Tokyo",
                            Name = "Japan",
                            Population = 126476461,
                            Size = 377975
                        },
                        new
                        {
                            Code = "JOR",
                            Capital = "Amman",
                            Name = "Jordan",
                            Population = 10203134,
                            Size = 89342
                        },
                        new
                        {
                            Code = "KAZ",
                            Capital = "Nur-Sultan",
                            Name = "Kazakhstan",
                            Population = 18776707,
                            Size = 2724900
                        },
                        new
                        {
                            Code = "KEN",
                            Capital = "Nairobi",
                            Name = "Kenya",
                            Population = 53771296,
                            Size = 580367
                        },
                        new
                        {
                            Code = "KIR",
                            Capital = "Tarawa",
                            Name = "Kiribati",
                            Population = 119449,
                            Size = 811
                        },
                        new
                        {
                            Code = "KWT",
                            Capital = "Kuwait City",
                            Name = "Kuwait",
                            Population = 4270571,
                            Size = 17818
                        },
                        new
                        {
                            Code = "KGZ",
                            Capital = "Bishkek",
                            Name = "Kyrgyzstan",
                            Population = 6524195,
                            Size = 199951
                        },
                        new
                        {
                            Code = "LAO",
                            Capital = "Vientiane",
                            Name = "Laos",
                            Population = 7275560,
                            Size = 236800
                        },
                        new
                        {
                            Code = "LVA",
                            Capital = "Riga",
                            Name = "Latvia",
                            Population = 1886198,
                            Size = 64559
                        },
                        new
                        {
                            Code = "LBN",
                            Capital = "Beirut",
                            Name = "Lebanon",
                            Population = 6825445,
                            Size = 10452
                        },
                        new
                        {
                            Code = "LSO",
                            Capital = "Maseru",
                            Name = "Lesotho",
                            Population = 2142249,
                            Size = 30355
                        },
                        new
                        {
                            Code = "LBR",
                            Capital = "Monrovia",
                            Name = "Liberia",
                            Population = 5057681,
                            Size = 111369
                        },
                        new
                        {
                            Code = "LBY",
                            Capital = "Tripoli",
                            Name = "Libya",
                            Population = 6871292,
                            Size = 1759540
                        },
                        new
                        {
                            Code = "LIE",
                            Capital = "Vaduz",
                            Name = "Liechtenstein",
                            Population = 38128,
                            Size = 160
                        },
                        new
                        {
                            Code = "LTU",
                            Capital = "Vilnius",
                            Name = "Lithuania",
                            Population = 2722289,
                            Size = 65300
                        },
                        new
                        {
                            Code = "LUX",
                            Capital = "Luxembourg",
                            Name = "Luxembourg",
                            Population = 634814,
                            Size = 2586
                        },
                        new
                        {
                            Code = "MDG",
                            Capital = "Antananarivo",
                            Name = "Madagascar",
                            Population = 27691018,
                            Size = 587041
                        },
                        new
                        {
                            Code = "MWI",
                            Capital = "Lilongwe",
                            Name = "Malawi",
                            Population = 19129952,
                            Size = 118484
                        },
                        new
                        {
                            Code = "MYS",
                            Capital = "Kuala Lumpur",
                            Name = "Malaysia",
                            Population = 32365999,
                            Size = 330803
                        },
                        new
                        {
                            Code = "MDV",
                            Capital = "Malé",
                            Name = "Maldives",
                            Population = 540544,
                            Size = 298
                        },
                        new
                        {
                            Code = "MLI",
                            Capital = "Bamako",
                            Name = "Mali",
                            Population = 20250833,
                            Size = 1240192
                        },
                        new
                        {
                            Code = "MLT",
                            Capital = "Valletta",
                            Name = "Malta",
                            Population = 514564,
                            Size = 316
                        },
                        new
                        {
                            Code = "MHL",
                            Capital = "Majuro",
                            Name = "Marshall Islands",
                            Population = 59190,
                            Size = 181
                        },
                        new
                        {
                            Code = "MRT",
                            Capital = "Nouakchott",
                            Name = "Mauritania",
                            Population = 4649658,
                            Size = 1030700
                        },
                        new
                        {
                            Code = "MUS",
                            Capital = "Port Louis",
                            Name = "Mauritius",
                            Population = 1271768,
                            Size = 2040
                        },
                        new
                        {
                            Code = "MEX",
                            Capital = "Mexico City",
                            Name = "Mexico",
                            Population = 128932753,
                            Size = 1964375
                        },
                        new
                        {
                            Code = "FSM",
                            Capital = "Palikir",
                            Name = "Micronesia",
                            Population = 115023,
                            Size = 702
                        },
                        new
                        {
                            Code = "MDA",
                            Capital = "Chișinău",
                            Name = "Moldova",
                            Population = 2657637,
                            Size = 33846
                        },
                        new
                        {
                            Code = "MCO",
                            Capital = "Monaco",
                            Name = "Monaco",
                            Population = 39242,
                            Size = 2
                        },
                        new
                        {
                            Code = "MNG",
                            Capital = "Ulaanbaatar",
                            Name = "Mongolia",
                            Population = 3278292,
                            Size = 1564110
                        },
                        new
                        {
                            Code = "MNE",
                            Capital = "Podgorica",
                            Name = "Montenegro",
                            Population = 622359,
                            Size = 13812
                        },
                        new
                        {
                            Code = "MAR",
                            Capital = "Rabat",
                            Name = "Morocco",
                            Population = 36910560,
                            Size = 446550
                        },
                        new
                        {
                            Code = "MOZ",
                            Capital = "Maputo",
                            Name = "Mozambique",
                            Population = 31255435,
                            Size = 801590
                        },
                        new
                        {
                            Code = "MMR",
                            Capital = "Naypyidaw",
                            Name = "Myanmar",
                            Population = 54409800,
                            Size = 676578
                        },
                        new
                        {
                            Code = "NAM",
                            Capital = "Windhoek",
                            Name = "Namibia",
                            Population = 2540905,
                            Size = 825615
                        },
                        new
                        {
                            Code = "NRU",
                            Capital = "Yaren",
                            Name = "Nauru",
                            Population = 10824,
                            Size = 21
                        },
                        new
                        {
                            Code = "NPL",
                            Capital = "Kathmandu",
                            Name = "Nepal",
                            Population = 29136808,
                            Size = 147181
                        },
                        new
                        {
                            Code = "NLD",
                            Capital = "Amsterdam",
                            Name = "Netherlands",
                            Population = 17134872,
                            Size = 41543
                        },
                        new
                        {
                            Code = "NZL",
                            Capital = "Wellington",
                            Name = "New Zealand",
                            Population = 4822233,
                            Size = 270467
                        },
                        new
                        {
                            Code = "NIC",
                            Capital = "Managua",
                            Name = "Nicaragua",
                            Population = 6624554,
                            Size = 130373
                        },
                        new
                        {
                            Code = "NER",
                            Capital = "Niamey",
                            Name = "Niger",
                            Population = 24206644,
                            Size = 1267000
                        },
                        new
                        {
                            Code = "NGA",
                            Capital = "Abuja",
                            Name = "Nigeria",
                            Population = 206139589,
                            Size = 923768
                        },
                        new
                        {
                            Code = "MKD",
                            Capital = "Skopje",
                            Name = "North Macedonia",
                            Population = 2083459,
                            Size = 25713
                        },
                        new
                        {
                            Code = "NOR",
                            Capital = "Oslo",
                            Name = "Norway",
                            Population = 5421241,
                            Size = 323802
                        },
                        new
                        {
                            Code = "OMN",
                            Capital = "Muscat",
                            Name = "Oman",
                            Population = 5106622,
                            Size = 309500
                        },
                        new
                        {
                            Code = "PAK",
                            Capital = "Islamabad",
                            Name = "Pakistan",
                            Population = 220892331,
                            Size = 881912
                        },
                        new
                        {
                            Code = "PLW",
                            Capital = "Ngerulmud",
                            Name = "Palau",
                            Population = 18094,
                            Size = 459
                        },
                        new
                        {
                            Code = "PSE",
                            Capital = "Ramallah",
                            Name = "Palestine State",
                            Population = 5101414,
                            Size = 6020
                        },
                        new
                        {
                            Code = "PAN",
                            Capital = "Panama City",
                            Name = "Panama",
                            Population = 4314767,
                            Size = 75417
                        },
                        new
                        {
                            Code = "PNG",
                            Capital = "Port Moresby",
                            Name = "Papua New Guinea",
                            Population = 8947027,
                            Size = 462840
                        },
                        new
                        {
                            Code = "PRY",
                            Capital = "Asunción",
                            Name = "Paraguay",
                            Population = 7132530,
                            Size = 406752
                        },
                        new
                        {
                            Code = "PER",
                            Capital = "Lima",
                            Name = "Peru",
                            Population = 32971854,
                            Size = 1285216
                        },
                        new
                        {
                            Code = "PHL",
                            Capital = "Manila",
                            Name = "Philippines",
                            Population = 109581078,
                            Size = 300000
                        },
                        new
                        {
                            Code = "POL",
                            Capital = "Warsaw",
                            Name = "Poland",
                            Population = 38386000,
                            Size = 312679
                        },
                        new
                        {
                            Code = "PRT",
                            Capital = "Lisbon",
                            Name = "Portugal",
                            Population = 10196709,
                            Size = 92212
                        },
                        new
                        {
                            Code = "QAT",
                            Capital = "Doha",
                            Name = "Qatar",
                            Population = 2881053,
                            Size = 11586
                        },
                        new
                        {
                            Code = "ROU",
                            Capital = "Bucharest",
                            Name = "Romania",
                            Population = 19237691,
                            Size = 238397
                        },
                        new
                        {
                            Code = "RUS",
                            Capital = "Moscow",
                            Name = "Russia",
                            Population = 145912025,
                            Size = 17098242
                        },
                        new
                        {
                            Code = "RWA",
                            Capital = "Kigali",
                            Name = "Rwanda",
                            Population = 12952218,
                            Size = 26338
                        },
                        new
                        {
                            Code = "KNA",
                            Capital = "Basseterre",
                            Name = "Saint Kitts and Nevis",
                            Population = 53199,
                            Size = 261
                        },
                        new
                        {
                            Code = "LCA",
                            Capital = "Castries",
                            Name = "Saint Lucia",
                            Population = 183627,
                            Size = 616
                        },
                        new
                        {
                            Code = "VCT",
                            Capital = "Kingstown",
                            Name = "Saint Vincent and the Grenadines",
                            Population = 110940,
                            Size = 389
                        },
                        new
                        {
                            Code = "WSM",
                            Capital = "Apia",
                            Name = "Samoa",
                            Population = 198414,
                            Size = 2842
                        },
                        new
                        {
                            Code = "SMR",
                            Capital = "San Marino",
                            Name = "San Marino",
                            Population = 33931,
                            Size = 61
                        },
                        new
                        {
                            Code = "STP",
                            Capital = "São Tomé",
                            Name = "Sao Tome and Principe",
                            Population = 219159,
                            Size = 964
                        },
                        new
                        {
                            Code = "SAU",
                            Capital = "Riyadh",
                            Name = "Saudi Arabia",
                            Population = 34813871,
                            Size = 2149690
                        },
                        new
                        {
                            Code = "SEN",
                            Capital = "Dakar",
                            Name = "Senegal",
                            Population = 16743927,
                            Size = 196722
                        },
                        new
                        {
                            Code = "SRB",
                            Capital = "Belgrade",
                            Name = "Serbia",
                            Population = 8772235,
                            Size = 88361
                        },
                        new
                        {
                            Code = "SYC",
                            Capital = "Victoria",
                            Name = "Seychelles",
                            Population = 98347,
                            Size = 455
                        },
                        new
                        {
                            Code = "SLE",
                            Capital = "Freetown",
                            Name = "Sierra Leone",
                            Population = 7976983,
                            Size = 71740
                        },
                        new
                        {
                            Code = "SGP",
                            Capital = "Singapore",
                            Name = "Singapore",
                            Population = 5850342,
                            Size = 710
                        },
                        new
                        {
                            Code = "SVK",
                            Capital = "Bratislava",
                            Name = "Slovakia",
                            Population = 5456362,
                            Size = 49037
                        },
                        new
                        {
                            Code = "SVN",
                            Capital = "Ljubljana",
                            Name = "Slovenia",
                            Population = 2078654,
                            Size = 20273
                        },
                        new
                        {
                            Code = "SLB",
                            Capital = "Honiara",
                            Name = "Solomon Islands",
                            Population = 686884,
                            Size = 28896
                        },
                        new
                        {
                            Code = "SOM",
                            Capital = "Mogadishu",
                            Name = "Somalia",
                            Population = 15893222,
                            Size = 637657
                        },
                        new
                        {
                            Code = "ZAF",
                            Capital = "Pretoria",
                            Name = "South Africa",
                            Population = 59308690,
                            Size = 1221037
                        },
                        new
                        {
                            Code = "KOR",
                            Capital = "Seoul",
                            Name = "South Korea",
                            Population = 51269185,
                            Size = 100210
                        },
                        new
                        {
                            Code = "SSD",
                            Capital = "Juba",
                            Name = "South Sudan",
                            Population = 11193725,
                            Size = 619745
                        },
                        new
                        {
                            Code = "ESP",
                            Capital = "Madrid",
                            Name = "Spain",
                            Population = 46754778,
                            Size = 505992
                        },
                        new
                        {
                            Code = "LKA",
                            Capital = "Sri Jayawardenepura Kotte",
                            Name = "Sri Lanka",
                            Population = 21413249,
                            Size = 65610
                        },
                        new
                        {
                            Code = "SDN",
                            Capital = "Khartoum",
                            Name = "Sudan",
                            Population = 43849260,
                            Size = 1886068
                        },
                        new
                        {
                            Code = "SUR",
                            Capital = "Paramaribo",
                            Name = "Suriname",
                            Population = 586634,
                            Size = 163820
                        },
                        new
                        {
                            Code = "SWE",
                            Capital = "Stockholm",
                            Name = "Sweden",
                            Population = 10099265,
                            Size = 450295
                        },
                        new
                        {
                            Code = "CHE",
                            Capital = "Bern",
                            Name = "Switzerland",
                            Population = 8654622,
                            Size = 41284
                        },
                        new
                        {
                            Code = "SYR",
                            Capital = "Damascus",
                            Name = "Syria",
                            Population = 17500657,
                            Size = 185180
                        },
                        new
                        {
                            Code = "TWN",
                            Capital = "Taipei",
                            Name = "Taiwan",
                            Population = 23816775,
                            Size = 36197
                        },
                        new
                        {
                            Code = "TJK",
                            Capital = "Dushanbe",
                            Name = "Tajikistan",
                            Population = 9537645,
                            Size = 143100
                        },
                        new
                        {
                            Code = "TZA",
                            Capital = "Dodoma",
                            Name = "Tanzania",
                            Population = 59734218,
                            Size = 945087
                        },
                        new
                        {
                            Code = "THA",
                            Capital = "Bangkok",
                            Name = "Thailand",
                            Population = 69799978,
                            Size = 513120
                        },
                        new
                        {
                            Code = "TLS",
                            Capital = "Dili",
                            Name = "Timor-Leste",
                            Population = 1318442,
                            Size = 14874
                        },
                        new
                        {
                            Code = "TGO",
                            Capital = "Lomé",
                            Name = "Togo",
                            Population = 8278724,
                            Size = 56785
                        },
                        new
                        {
                            Code = "TON",
                            Capital = "Nuku'alofa",
                            Name = "Tonga",
                            Population = 105697,
                            Size = 747
                        },
                        new
                        {
                            Code = "TTO",
                            Capital = "Port of Spain",
                            Name = "Trinidad and Tobago",
                            Population = 1399488,
                            Size = 5130
                        },
                        new
                        {
                            Code = "TUN",
                            Capital = "Tunis",
                            Name = "Tunisia",
                            Population = 11818618,
                            Size = 163610
                        },
                        new
                        {
                            Code = "TUR",
                            Capital = "Ankara",
                            Name = "Turkey",
                            Population = 84339067,
                            Size = 783356
                        },
                        new
                        {
                            Code = "TKM",
                            Capital = "Ashgabat",
                            Name = "Turkmenistan",
                            Population = 6031200,
                            Size = 491210
                        },
                        new
                        {
                            Code = "TUV",
                            Capital = "Funafuti",
                            Name = "Tuvalu",
                            Population = 11792,
                            Size = 26
                        },
                        new
                        {
                            Code = "UGA",
                            Capital = "Kampala",
                            Name = "Uganda",
                            Population = 45741007,
                            Size = 241038
                        },
                        new
                        {
                            Code = "UKR",
                            Capital = "Kyiv",
                            Name = "Ukraine",
                            Population = 44134693,
                            Size = 603500
                        },
                        new
                        {
                            Code = "ARE",
                            Capital = "Abu Dhabi",
                            Name = "United Arab Emirates",
                            Population = 9890402,
                            Size = 83600
                        },
                        new
                        {
                            Code = "GBR",
                            Capital = "London",
                            Name = "United Kingdom",
                            Population = 67886011,
                            Size = 242495
                        },
                        new
                        {
                            Code = "USA",
                            Capital = "Washington, D.C.",
                            Name = "United States",
                            Population = 331002651,
                            Size = 9833520
                        },
                        new
                        {
                            Code = "URY",
                            Capital = "Montevideo",
                            Name = "Uruguay",
                            Population = 3473730,
                            Size = 176215
                        },
                        new
                        {
                            Code = "UZB",
                            Capital = "Tashkent",
                            Name = "Uzbekistan",
                            Population = 33469203,
                            Size = 448978
                        },
                        new
                        {
                            Code = "VUT",
                            Capital = "Port Vila",
                            Name = "Vanuatu",
                            Population = 307145,
                            Size = 12189
                        },
                        new
                        {
                            Code = "VAT",
                            Capital = "Vatican City",
                            Name = "Vatican City",
                            Population = 825,
                            Size = 0
                        },
                        new
                        {
                            Code = "VEN",
                            Capital = "Caracas",
                            Name = "Venezuela",
                            Population = 28435943,
                            Size = 916445
                        },
                        new
                        {
                            Code = "VNM",
                            Capital = "Hanoi",
                            Name = "Vietnam",
                            Population = 97338579,
                            Size = 331212
                        },
                        new
                        {
                            Code = "YEM",
                            Capital = "Sana'a",
                            Name = "Yemen",
                            Population = 29825964,
                            Size = 527968
                        },
                        new
                        {
                            Code = "ZMB",
                            Capital = "Lusaka",
                            Name = "Zambia",
                            Population = 18383955,
                            Size = 752612
                        },
                        new
                        {
                            Code = "ZWE",
                            Capital = "Harare",
                            Name = "Zimbabwe",
                            Population = 14862924,
                            Size = 390757
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
